{% set name = "pytest-pretty" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest_pretty-{{ version }}.tar.gz
  sha256: 425e116c1ed10ce67eeb688f22d1bcb91ca58a97986026bf42c0717da80740b3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python >=3.7
  run:
    - pytest >=7
    - python >=3.7
    - rich >=12

test:
  imports:
    - pytest_pretty
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/samuelcolvin/pytest-pretty
  summary: Pytest plugin for pretty printing the test summary.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
