{% set name = "pytest-pretty" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_pretty-{{ version }}.tar.gz
  sha256: 105a355f128e392860ad2c478ae173ff96d2f03044692f9818ff3d49205d3a60

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - pytest >=7
    - python >={{ python_min }}
    - rich >=12

test:
  imports:
    - pytest_pretty
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/samuelcolvin/pytest-pretty
  summary: Pytest plugin for pretty printing the test summary.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
